import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";

const Contacts = () => {
  const { t } = useTranslation('contacts');

  return <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome
      </h1>

      <div className={styles.grid}>
        <Link href="/">
          <a className={styles.card}>
            <h2>{t('indexTitle')}</h2>
            <p>{t('indexDesc')}</p>
          </a>
        </Link>


        <Link href="/contacts">
        <a className={styles.card}>
          <h2>{t('contacts')}</h2>
        </a>
        </Link>
      </div>
    </main>
  </div>
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['contacts']),
  }
})

export default Contacts;
